# App keys
SECRET_KEY_BASE: '<%=
  token = StringIO.new
  IO.popen("rake secret") do |pipe|
    pipe.each do |line|
      token.print(line.chomp)
    end
  end
  token.string
%>'

development:
  DB_NAME: <%= app_name %>_development
  DB_USER: postgres
  DB_PASSWORD:

test:
  DB_NAME: <%= app_name %>_test
  DB_USER: postgres
  DB_PASSWORD:

production:
  DB_NAME: <%= app_name %>_production
  DB_USER: postgres
  DB_PASSWORD:

# Third party keys
# ...